{{- $secretName := .Values.ingress.tls.secretName | default (printf "%s-tls" (include "skillhub.fullname" .)) }}
{{- if and .Values.ingress.enabled .Values.ingress.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $secretName }}-cert
  labels:
    {{- include "skillhub.labels" . | nindent 4 }}
spec:
  secretName: {{ $secretName }}
  duration: 2160h
  renewBefore: 360h
  dnsNames:
    - {{ .Values.ingress.host }}
  issuerRef:
    name: {{ .Values.ingress.certManager.issuerName }}
    kind: {{ .Values.ingress.certManager.issuerKind }}
{{- end }}
