{{- if and .Values.server.enabled (not .Values.s3.enabled) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "skillhub.fullname" . }}-server-data
  labels:
    {{- include "skillhub.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  {{- $accessMode := .Values.server.storage.accessMode }}
  {{- if not $accessMode }}
  {{- if or (gt (.Values.server.replicaCount | int) 1) (and .Values.server.autoscaling.enabled (gt (.Values.server.autoscaling.maxReplicas | int) 1)) }}
  {{- $accessMode = "ReadWriteMany" }}
  {{- else }}
  {{- $accessMode = "ReadWriteOnce" }}
  {{- end }}
  {{- end }}
  accessModes:
    - {{ $accessMode }}
  {{- if .Values.server.storage.storageClassName }}
  storageClassName: {{ .Values.server.storage.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.server.storage.size }}
{{- end }}
